Repository knative/infra, pull requests merged in 2022-04, with the labels that each got.

#3 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, size/S, approved

#6 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#8 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#9 Add template for PRs
  .github/pull-request-template.md
Labels: lgtm, size/S, approved

#4 Initial repo reorg change
  README.md
  prow/README.md
  prow/cluster-definitions/README.md
  prow/configs/README.md
  prow/job-definitions/README.md
  prow/jobs/README.md
Labels: lgtm, approved, size/L

#12 CODE_OF_CONDUCT update
  CODE_OF_CONDUCT.md
Labels: lgtm, approved, size/XS

#13 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
