Repository knative/infra, pull requests merged in 2023-07, with the labels that each got.

#117 Support added for kn-plugin-event on ppc64le
  prow/jobs/generated/knative-sandbox/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.10.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.9.gen.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.10.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.9.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event.yaml
Labels: lgtm, ok-to-test, approved, size/L

#119 Java Version to 20
  images/prow-tests/Dockerfile
Labels: lgtm, approved, size/XS

#120 SSL_CERT_FILE variable path modified for kn-plugin-event
  prow/jobs/generated/knative-sandbox/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.10.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.9.gen.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.10.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.9.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event.yaml
Labels: lgtm, ok-to-test, size/S, approved

#124 allow functions leads to rerun prowjobs
  prow/config.yaml
Labels: lgtm, approved, size/XS

#125 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#127 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#128 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#130 chore: Update Go version in prow-tests image
  images/prow-tests/Dockerfile
  images/tool/Dockerfile
Labels: lgtm, approved, size/XS

#142 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#148 [s390x] adding support for release 1.11
  prow/jobs/generated/knative-sandbox/eventing-kafka-broker-release-1.11.gen.yaml
  prow/jobs/generated/knative-sandbox/eventing-kafka-release-1.11.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.11.gen.yaml
  prow/jobs/generated/knative/client-release-1.11.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
  prow/jobs/generated/knative/serving-release-1.11.gen.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-broker-release-1.11.yaml
  prow/jobs_config/knative-sandbox/eventing-kafka-release-1.11.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.11.yaml
  prow/jobs_config/knative/client-release-1.11.yaml
  prow/jobs_config/knative/eventing-release-1.11.yaml
  prow/jobs_config/knative/serving-release-1.11.yaml
Labels: lgtm, size/XL, approved

#150 ppc64le cron job timings modified
  prow/jobs/generated/knative-sandbox/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.10.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.11.gen.yaml
  prow/jobs/generated/knative-sandbox/kn-plugin-event-release-1.9.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.10.gen.yaml
  prow/jobs/generated/knative/client-release-1.11.gen.yaml
  prow/jobs/generated/knative/client-release-1.9.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.10.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.9.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.10.gen.yaml
  prow/jobs/generated/knative/operator-release-1.11.gen.yaml
  prow/jobs/generated/knative/operator-release-1.9.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.10.gen.yaml
  prow/jobs/generated/knative/serving-release-1.11.gen.yaml
  prow/jobs/generated/knative/serving-release-1.9.gen.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.10.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.11.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event-release-1.9.yaml
  prow/jobs_config/knative-sandbox/kn-plugin-event.yaml
  prow/jobs_config/knative/client-release-1.10.yaml
  prow/jobs_config/knative/client-release-1.11.yaml
  prow/jobs_config/knative/client-release-1.9.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing-release-1.10.yaml
  prow/jobs_config/knative/eventing-release-1.11.yaml
  prow/jobs_config/knative/eventing-release-1.9.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/operator-release-1.10.yaml
  prow/jobs_config/knative/operator-release-1.11.yaml
  prow/jobs_config/knative/operator-release-1.9.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving-release-1.10.yaml
  prow/jobs_config/knative/serving-release-1.11.yaml
  prow/jobs_config/knative/serving-release-1.9.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, ok-to-test, approved, size/L

#138 Add `cr` and `helm` cli tools
  images/prow-tests/Dockerfile
Labels: lgtm, size/S, approved

#153 Auto merge dependabot updates
  .github/dependabot.yml
Labels: lgtm, approved, size/XS
