Repository knative/infra, pull requests merged in 2023-06, with the labels that each got.

#89 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#90 Update the image-bumper config to use the new image location
  prow/autobump-config/knative-flaky-test-reporter.yaml
  prow/autobump-config/knative-prow-tests.yaml
  prow/jobs/custom/infra.yaml
Labels: lgtm, approved, size/XS

#91 Install the fixed version of `release-jobs-syncer`
  images/prow-tests/Dockerfile
Labels: lgtm, approved, size/XS

#93 Update the path for `flaky-test-recorder`
  prow/jobs/custom/infra.yaml
Labels: lgtm, approved, size/XS

#95 Last of test-infra
  images/prow-tests/README.md
  prow/cluster/monitoring/mixins/prometheus/ci_absent_alerts.libsonnet
  prow/cluster/monitoring/mixins/prometheus/plank_alerts.libsonnet
  prow/jobs/generated/knative/test-infra-main.gen.yaml
  prow/jobs_config/knative/test-infra.yaml
Labels: lgtm, size/M, approved

#96 Build `flaky-test-reporter` in the prow-tests image
  images/prow-tests/Dockerfile
  prow/jobs/custom/infra.yaml
Labels: lgtm, size/M, approved

#97 Use the prow-tests image for flaky jobs and bump release-jobs-syncer image
  prow/jobs/custom/infra.yaml
Labels: lgtm, size/S, approved

#102 Run flaky-test-reporter recorder with the correct flags
  prow/jobs/custom/infra.yaml
Labels: lgtm, approved, size/XS

#104 chore: add unit and integration test config for func
  prow/jobs/generated/knative/func-main.gen.yaml
  prow/jobs_config/knative/func.yaml
Labels: lgtm, approved, size/L

#107 chore: remove jobs for func
  prow/jobs/generated/knative/func-main.gen.yaml
  prow/jobs_config/knative/func.yaml
Labels: lgtm, approved, size/L

#109 Bump java to 17 and install it from temurin/ecplise
  images/prow-tests/Dockerfile
  images/prow-tests/cloudbuild-test.yaml
  images/prow-tests/cloudbuild.yaml
  images/simple-image.mk
Labels: lgtm, size/S, approved

#111 Fix buildx flags
  images/prow-tests/cloudbuild.yaml
Labels: lgtm, approved, size/XS

#113 Make Github Actions optional for eventing-istio
  prow/config.yaml
Labels: lgtm, approved, size/XS

#115 chore: add presubmit job for func unit tests
  prow/jobs/generated/knative/func-main.gen.yaml
  prow/jobs_config/knative/func.yaml
Labels: lgtm, size/M, approved

#116 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review
