Repository knative/infra, pull requests merged in 2023-10, with the labels that each got.

#225 cron job timings modified for ppc64le jobs
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.10.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.9.gen.yaml
  prow/jobs/generated/knative/client-release-1.10.gen.yaml
  prow/jobs/generated/knative/client-release-1.11.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.10.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.9.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.10.gen.yaml
  prow/jobs/generated/knative/operator-release-1.11.gen.yaml
  prow/jobs/generated/knative/operator-release-1.9.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.10.gen.yaml
  prow/jobs/generated/knative/serving-release-1.11.gen.yaml
  prow/jobs/generated/knative/serving-release-1.9.gen.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.10.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.11.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.9.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event.yaml
  prow/jobs_config/knative/client-release-1.10.yaml
  prow/jobs_config/knative/client-release-1.11.yaml
  prow/jobs_config/knative/eventing-release-1.10.yaml
  prow/jobs_config/knative/eventing-release-1.11.yaml
  prow/jobs_config/knative/eventing-release-1.9.yaml
  prow/jobs_config/knative/operator-release-1.10.yaml
  prow/jobs_config/knative/operator-release-1.11.yaml
  prow/jobs_config/knative/operator-release-1.9.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving-release-1.10.yaml
  prow/jobs_config/knative/serving-release-1.11.yaml
  prow/jobs_config/knative/serving-release-1.9.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, ok-to-test, size/M, approved

#227 Support added for kafka-broker on ppc64le
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.10.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.9.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.10.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.11.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.9.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
Labels: lgtm, ok-to-test, size/XXL, approved

#228 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#231 [main] Update community files
  OWNERS_ALIASES
Labels: lgtm, approved, size/XS, skip-review

#232 Bump Go verions to latest patch release
  images/prow-tests/Dockerfile
  images/tool/Dockerfile
Labels: lgtm, approved, size/XS

#236 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review
