Repository knative/infra, pull requests merged in 2023-05, with the labels that each got.

#65 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#68 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#71 Point infra jobs to the new Infra repo
  prow/config.yaml
  prow/jobs/custom/autobump-flaky-test-reporter.yaml
  prow/jobs/custom/autobump-prow-tests.yaml
  prow/jobs/custom/autobump-prow.yaml
  prow/jobs/custom/autodeploy-prow.yaml
  prow/jobs/custom/branchprotector.yaml
  prow/jobs/custom/label-sync.yaml
Labels: lgtm, size/M, approved

#72 Upgrade ArgoCD and point the apps to the new repo
  prow/cluster/gitops/apps/monitoring.yaml
  prow/cluster/gitops/apps/prow-build.yaml
  prow/cluster/gitops/apps/prow-trusted.yaml
  prow/cluster/gitops/apps/prow.yaml
  prow/cluster/gitops/apps/shared.yaml
  prow/cluster/gitops/bootstrap/apps.yaml
  prow/cluster/gitops/bootstrap/kustomization.yaml
  prow/jobs/custom/test-infra.yaml
Labels: lgtm, size/S, approved

#74 Enable config-updater for the new repo
  prow/autobump-config/knative-flaky-test-reporter.yaml
  prow/autobump-config/knative-prow-tests.yaml
  prow/autobump-config/knative.yaml
  prow/jobs/custom/branchprotector.yaml
  prow/plugins.yaml
Labels: lgtm, size/S, approved

#75 Delete jobs from old repository
  prow/jobs/custom/infra.yaml
  prow/jobs/custom/test-infra.yaml
Labels: lgtm, size/XL, approved

#78 Install tools from knative/toolbox repo and bump stuff
  images/prow-tests/Dockerfile
  tools/configgen/go.mod
  tools/configgen/go.sum
  tools/configgen/main.go
  tools/configgen/pkg/testgrid.go
Labels: lgtm, size/M, approved

#83 Build release-jobs-syncer as part of the image
  images/prow-tests/Dockerfile
  images/prow-tests/cloudbuild.yaml
Labels: lgtm, size/S, approved
