Repository knative/infra, pull requests merged in 2023-08, with the labels that each got.

#159 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#162 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#166 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#167 Modified the registry configs to use nip.io based dns
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.10.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.9.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.10.gen.yaml
  prow/jobs/generated/knative/client-release-1.11.gen.yaml
  prow/jobs/generated/knative/client-release-1.9.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.10.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.9.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.10.gen.yaml
  prow/jobs/generated/knative/operator-release-1.11.gen.yaml
  prow/jobs/generated/knative/operator-release-1.9.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.10.gen.yaml
  prow/jobs/generated/knative/serving-release-1.11.gen.yaml
  prow/jobs/generated/knative/serving-release-1.9.gen.yaml
  prow/jobs_config/.base.yaml
  prow/jobs_config/knative/serving-release-1.10.yaml
  prow/jobs_config/knative/serving-release-1.11.yaml
  prow/jobs_config/knative/serving-release-1.9.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/M, needs-ok-to-test, approved

#171 add e2e cluster region var to jobs
  prow/jobs/generated/knative-extensions/async-component-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-autoscaler-keda-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-awssqs-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-ceph-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-couchdb-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-github-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-gitlab-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-istio-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kogito-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-natss-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-rabbitmq-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-redis-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-admin-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-operator-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-quickstart-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-service-log-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-source-kafka-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-source-kamelet-main.gen.yaml
  prow/jobs/generated/knative-extensions/net-certmanager-main.gen.yaml
  prow/jobs/generated/knative-extensions/net-contour-main.gen.yaml
  prow/jobs/generated/knative-extensions/net-gateway-api-main.gen.yaml
  prow/jobs/generated/knative-extensions/net-http01-main.gen.yaml
  prow/jobs/generated/knative-extensions/net-istio-main.gen.yaml
  prow/jobs/generated/knative-extensions/net-kourier-main.gen.yaml
  prow/jobs/generated/knative-extensions/sample-controller-main.gen.yaml
  prow/jobs/generated/knative-extensions/sample-source-main.gen.yaml
  prow/jobs/generated/knative-extensions/scaling-group-main.gen.yaml
  prow/jobs/generated/knative-extensions/security-guard-main.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/func-main.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/.base.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/M, approved

#175 KO_DOCKER repo modified
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.10.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.9.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.10.gen.yaml
  prow/jobs/generated/knative/client-release-1.11.gen.yaml
  prow/jobs/generated/knative/client-release-1.9.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.10.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.9.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.10.gen.yaml
  prow/jobs/generated/knative/operator-release-1.11.gen.yaml
  prow/jobs/generated/knative/operator-release-1.9.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.10.gen.yaml
  prow/jobs/generated/knative/serving-release-1.11.gen.yaml
  prow/jobs/generated/knative/serving-release-1.9.gen.yaml
  prow/jobs_config/.base.yaml
Labels: lgtm, size/M, needs-ok-to-test, approved
