Repository knative/infra, pull requests merged in 2023-11, with the labels that each got.

#254 add release 1.12 jobs for s390x
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.12.gen.yaml
  prow/jobs/generated/knative/client-release-1.12.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.12.gen.yaml
  prow/jobs/generated/knative/operator-release-1.12.gen.yaml
  prow/jobs/generated/knative/serving-release-1.12.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.12.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-release-1.12.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.12.yaml
  prow/jobs_config/knative/client-release-1.12.yaml
  prow/jobs_config/knative/eventing-release-1.12.yaml
  prow/jobs_config/knative/operator-release-1.12.yaml
  prow/jobs_config/knative/serving-release-1.12.yaml
Labels: lgtm, size/XL, approved

#258 Add release 1.12 jobs on ppc64le
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.12.gen.yaml
  prow/jobs/generated/knative/client-release-1.11.gen.yaml
  prow/jobs/generated/knative/client-release-1.12.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.12.gen.yaml
  prow/jobs/generated/knative/operator-release-1.11.gen.yaml
  prow/jobs/generated/knative/operator-release-1.12.gen.yaml
  prow/jobs/generated/knative/serving-release-1.11.gen.yaml
  prow/jobs/generated/knative/serving-release-1.12.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.12.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.12.yaml
  prow/jobs_config/knative/client-release-1.11.yaml
  prow/jobs_config/knative/client-release-1.12.yaml
  prow/jobs_config/knative/eventing-release-1.11.yaml
  prow/jobs_config/knative/eventing-release-1.12.yaml
  prow/jobs_config/knative/operator-release-1.11.yaml
  prow/jobs_config/knative/operator-release-1.12.yaml
  prow/jobs_config/knative/serving-release-1.11.yaml
  prow/jobs_config/knative/serving-release-1.12.yaml
Labels: lgtm, needs-ok-to-test, approved, size/L

#259 use renamed script and param for external-domain-tls
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/M, approved

#266 Make SECURITY.md consistent
  SECURITY.md
Labels: lgtm, do-not-merge/hold, approved, size/XS

#274 cronjob timings modified for knative ppc64le jobs
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.10.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.10.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.12.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.10.gen.yaml
  prow/jobs/generated/knative/client-release-1.11.gen.yaml
  prow/jobs/generated/knative/client-release-1.12.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.10.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.12.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.10.gen.yaml
  prow/jobs/generated/knative/operator-release-1.11.gen.yaml
  prow/jobs/generated/knative/operator-release-1.12.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.10.gen.yaml
  prow/jobs/generated/knative/serving-release-1.11.gen.yaml
  prow/jobs/generated/knative/serving-release-1.12.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.10.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.11.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.12.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.10.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.11.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.12.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event.yaml
  prow/jobs_config/knative/client-release-1.10.yaml
  prow/jobs_config/knative/client-release-1.11.yaml
  prow/jobs_config/knative/client-release-1.12.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing-release-1.10.yaml
  prow/jobs_config/knative/eventing-release-1.11.yaml
  prow/jobs_config/knative/eventing-release-1.12.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/operator-release-1.10.yaml
  prow/jobs_config/knative/operator-release-1.11.yaml
  prow/jobs_config/knative/operator-release-1.12.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving-release-1.10.yaml
  prow/jobs_config/knative/serving-release-1.11.yaml
  prow/jobs_config/knative/serving-release-1.12.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, needs-ok-to-test, approved, size/L

#277 Add clotributor link to readme
  README.md
Labels: lgtm, approved, size/XS

#278 Bump argocd, Grafana and ESO
  .gitignore
  prow/cluster/gitops/apps/eso-prow-build.yaml
  prow/cluster/gitops/apps/eso-prow.yaml
  prow/cluster/gitops/apps/eso-trusted.yaml
  prow/cluster/gitops/bootstrap/kustomization.yaml
  prow/cluster/monitoring/chart/Chart.lock
  prow/cluster/monitoring/chart/Chart.yaml
  prow/cluster/monitoring/chart/values.yaml
Labels: lgtm, size/M, approved

#281 Bump Golang to latest patch release
  images/prow-tests/Dockerfile
  images/tool/Dockerfile
Labels: lgtm, approved, size/XS
