Repository knative/infra, pull requests merged in 2023-12, with the labels that each got.

#284 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#283 Bump go-licenses to new version
  images/prow-tests/Dockerfile
Labels: lgtm, approved, size/XS

#261 Bumping for next JDK version
  images/prow-tests/Dockerfile
Labels: lgtm, approved, size/XS

#296 Bump Golang to 1.21.5
  images/prow-tests/Dockerfile
  images/tool/Dockerfile
Labels: lgtm, approved, size/XS

#299 knative contour serving jobs for ppc64le removed
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.10.gen.yaml
  prow/jobs/generated/knative/serving-release-1.11.gen.yaml
  prow/jobs/generated/knative/serving-release-1.12.gen.yaml
  prow/jobs_config/knative/serving-release-1.10.yaml
  prow/jobs_config/knative/serving-release-1.11.yaml
  prow/jobs_config/knative/serving-release-1.12.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, ok-to-test, approved, size/L

#288 Turn on signing and attestation for serving
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/S, approved
