Repository knative/infra, pull requests merged in 2023-09, with the labels that each got.

#181 drop dedicated grafana instance for performance test results
  infra/gcp/dns/dns.tf
  infra/k8s/shared/grafana-dashboard.json
  infra/k8s/shared/grafana-deployment.yaml
Labels: lgtm, size/XL, approved

#182 add new prow target for performance tests
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/M, approved

#184 Bump go to 1.21
  images/prow-tests/Dockerfile
  images/tool/Dockerfile
Labels: lgtm, approved, size/XS

#185 increase timeout for performance tests
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, approved, size/XS

#189 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#191 add `envsubst` to prow builder image
  images/prow-tests/Dockerfile
Labels: lgtm, approved, size/XS

#193 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#194 always trust dependabot PRs
  prow/plugins.yaml
Labels: lgtm, approved, size/XS

#188 Added KEDA reconciler test to ekb
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
Labels: lgtm, size/M, approved

#197 minor bump for golang
  images/prow-tests/Dockerfile
  images/tool/Dockerfile
Labels: lgtm, approved, size/XS

#205 update continuous performance test jobs
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, approved, size/L

#206 drop CI for kperf as it is archived
  README.md
  prow/jobs/generated/knative-extensions/kperf-main.gen.yaml
  prow/jobs_config/knative-extensions/kperf.yaml
Labels: lgtm, approved, size/L

#204 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#213 Drop istio HEAD testing
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, approved, size/L

#214 pin rust to bullseye to compile rcodesign properly
  images/prow-tests/Dockerfile
Labels: lgtm, size/M, approved

#217 Use correct image
  prow/jobs/generated/knative-extensions/serving-progressive-rollout-main.gen.yaml
  prow/jobs_config/knative-extensions/serving-progressive-rollout.yaml
Labels: lgtm, size/S, approved

#215 Make Loom and KEDA tests on demand tests
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
Labels: lgtm, size/S, approved

#216 ppc64le specific changes added to prow config
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.10.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.9.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.10.gen.yaml
  prow/jobs/generated/knative/client-release-1.11.gen.yaml
  prow/jobs/generated/knative/client-release-1.9.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.10.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.9.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.10.gen.yaml
  prow/jobs/generated/knative/operator-release-1.11.gen.yaml
  prow/jobs/generated/knative/operator-release-1.9.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.10.gen.yaml
  prow/jobs/generated/knative/serving-release-1.11.gen.yaml
  prow/jobs/generated/knative/serving-release-1.9.gen.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.10.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.11.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.9.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event.yaml
  prow/jobs_config/knative/client-release-1.10.yaml
  prow/jobs_config/knative/client-release-1.11.yaml
  prow/jobs_config/knative/client-release-1.9.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing-release-1.10.yaml
  prow/jobs_config/knative/eventing-release-1.11.yaml
  prow/jobs_config/knative/eventing-release-1.9.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/operator-release-1.10.yaml
  prow/jobs_config/knative/operator-release-1.11.yaml
  prow/jobs_config/knative/operator-release-1.9.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving-release-1.10.yaml
  prow/jobs_config/knative/serving-release-1.11.yaml
  prow/jobs_config/knative/serving-release-1.9.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, ok-to-test, approved, size/L

#220 Add a secret into ppc64le-cluster secret store
  prow/cluster/build/secrets.yaml
Labels: lgtm, needs-ok-to-test, approved, size/XS

#221 automerge dependabot PRs
  prow/config.yaml
Labels: lgtm, size/S, approved
