Repository knative/infra, pull requests merged in 2024-05, with the labels that each got.

#428 [s390x]: add s390x specific prow job config for release-1.14
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.13.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.14.gen.yaml
  prow/jobs/generated/knative/client-release-1.13.gen.yaml
  prow/jobs/generated/knative/client-release-1.14.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.13.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.14.gen.yaml
  prow/jobs/generated/knative/operator-release-1.13.gen.yaml
  prow/jobs/generated/knative/operator-release-1.14.gen.yaml
  prow/jobs/generated/knative/serving-release-1.13.gen.yaml
  prow/jobs/generated/knative/serving-release-1.14.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.14.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-release-1.12.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-release-1.13.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.14.yaml
  prow/jobs_config/knative/client-release-1.13.yaml
  prow/jobs_config/knative/client-release-1.14.yaml
  prow/jobs_config/knative/eventing-release-1.13.yaml
  prow/jobs_config/knative/eventing-release-1.14.yaml
  prow/jobs_config/knative/operator-release-1.13.yaml
  prow/jobs_config/knative/operator-release-1.14.yaml
  prow/jobs_config/knative/serving-release-1.13.yaml
  prow/jobs_config/knative/serving-release-1.14.yaml
Labels: lgtm, size/XXL, approved

#431 [ppc64le]: add ppc64le specific prow job config for release-1.14
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.14.gen.yaml
  prow/jobs/generated/knative/client-release-1.14.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.14.gen.yaml
  prow/jobs/generated/knative/operator-release-1.14.gen.yaml
  prow/jobs/generated/knative/serving-release-1.14.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.14.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.14.yaml
  prow/jobs_config/knative/client-release-1.14.yaml
  prow/jobs_config/knative/eventing-release-1.14.yaml
  prow/jobs_config/knative/operator-release-1.14.yaml
  prow/jobs_config/knative/serving-release-1.14.yaml
Labels: lgtm, size/XL, needs-ok-to-test, approved

#434 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#440 Added the repo autoscaler-keda
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/jobs/generated/knative-extensions/autoscaler-keda-main.gen.yaml
  prow/jobs_config/knative-extensions/autoscaler-keda.yaml
Labels: lgtm, approved, size/L

#398 Move tests from net-certmanager to serving
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, approved, size/L

#442 cert manager test is running the wrong tests disable it for now
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/M, approved

#445 Add back certmanager tests
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/M, approved

#443 drop net-http01 prow jobs
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/jobs/generated/knative-extensions/net-http01-main.gen.yaml
  prow/jobs/generated/knative-extensions/net-http01-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/net-http01-release-1.12.gen.yaml
  prow/jobs_config/knative-extensions/net-http01-release-1.11.yaml
  prow/jobs_config/knative-extensions/net-http01-release-1.12.yaml
  prow/jobs_config/knative-extensions/net-http01.yaml
Labels: lgtm, size/XL, approved

#446 Drop prow jobs for archived repos
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/jobs/generated/knative-extensions/eventing-awssqs-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-awssqs-release-1.1.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-awssqs-release-1.2.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-couchdb-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-couchdb-release-1.0.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-couchdb-release-1.1.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.13.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-natss-release-1.10.gen.yaml
  prow/jobs_config/knative-extensions/eventing-awssqs-release-1.1.yaml
  prow/jobs_config/knative-extensions/eventing-awssqs-release-1.2.yaml
  prow/jobs_config/knative-extensions/eventing-awssqs.yaml
  prow/jobs_config/knative-extensions/eventing-couchdb-release-1.0.yaml
  prow/jobs_config/knative-extensions/eventing-couchdb-release-1.1.yaml
  prow/jobs_config/knative-extensions/eventing-couchdb.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-release-1.12.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-release-1.13.yaml
  prow/jobs_config/knative-extensions/eventing-kafka.yaml
  prow/jobs_config/knative-extensions/eventing-natss-release-1.10.yaml
Labels: lgtm, size/XXL, approved

#449 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#450 Fix istio no-mesh build command
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, approved, size/XS

#451 [net-gateway-api] add envoy gateway presubmits
  prow/jobs/generated/knative-extensions/net-gateway-api-main.gen.yaml
  prow/jobs_config/knative-extensions/net-gateway-api.yaml
Labels: lgtm, size/M, approved
