Repository knative/infra, pull requests merged in 2024-03, with the labels that each got.

#376 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#381 add prow job to test gateway api and contour
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/M, approved

#383 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#387 fix: bumped cosign to v1.13.6
  images/prow-tests/Dockerfile
Labels: lgtm, approved, size/XS

#390 [main] Update community files
  OWNERS_ALIASES
Labels: size/S, skip-review

#391 bump: ekb release-1.13 now uses updated base image
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.13.yaml
Labels: lgtm, size/M, approved
