Repository knative/infra, pull requests merged in 2024-08, with the labels that each got.

#494 reduce job frequencies for release branches and serving e2e's
  prow/cluster/build/boskos-janitor.yaml
  prow/jobs/generated/knative-extensions/backstage-plugins-release-0.1.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-autoscaler-keda-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-autoscaler-keda-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-ceph-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-ceph-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-github-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-github-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-gitlab-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-gitlab-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-istio-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-istio-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kogito-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kogito-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-natss-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-natss-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-rabbitmq-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-rabbitmq-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-redis-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-redis-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-admin-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-admin-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-operator-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-operator-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-quickstart-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-quickstart-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-service-log-release-1.1.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-source-kafka-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-source-kafka-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-source-kamelet-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-source-kamelet-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/net-contour-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/net-contour-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/net-istio-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/net-istio-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/net-kourier-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/net-kourier-release-1.15.gen.yaml
  prow/jobs/generated/knative-extensions/security-guard-release-0.5.gen.yaml
  prow/jobs/generated/knative-extensions/security-guard-release-0.6.gen.yaml
  prow/jobs/generated/knative-extensions/serving-progressive-rollout-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/serving-progressive-rollout-release-1.15.gen.yaml
  prow/jobs/generated/knative/client-release-1.14.gen.yaml
  prow/jobs/generated/knative/client-release-1.15.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.14.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.15.gen.yaml
  prow/jobs/generated/knative/operator-release-1.14.gen.yaml
  prow/jobs/generated/knative/operator-release-1.15.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.14.gen.yaml
  prow/jobs/generated/knative/serving-release-1.15.gen.yaml
  prow/jobs_config/knative/serving.yaml
  tools/configgen/pkg/scheduler.go
Labels: lgtm, approved, size/L

#497 drop s390x/ppc ci jobs
  prow/cluster/build/secrets.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.14.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.14.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.14.gen.yaml
  prow/jobs/generated/knative/client-release-1.15.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.14.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.15.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.14.gen.yaml
  prow/jobs/generated/knative/operator-release-1.15.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.14.gen.yaml
  prow/jobs/generated/knative/serving-release-1.15.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.14.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.14.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event.yaml
  prow/jobs_config/knative/client-release-1.14.yaml
  prow/jobs_config/knative/client-release-1.15.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing-release-1.14.yaml
  prow/jobs_config/knative/eventing-release-1.15.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/operator-release-1.14.yaml
  prow/jobs_config/knative/operator-release-1.15.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving-release-1.14.yaml
  prow/jobs_config/knative/serving-release-1.15.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/XXL, approved

#499 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#501 Install NodeJS in Prow image
  images/prow-tests/Dockerfile
Labels: lgtm, size/S, approved

#503 Optimise GCP cloud spend
  infra/gcp/.terraform.lock.hcl
  infra/gcp/boskos/.terraform.lock.hcl
  infra/gcp/boskos/main.tf
  infra/gcp/boskos/provider.tf
  infra/gcp/dns/dns.tf
  infra/gcp/gsuite/gsuite.tf
  infra/gcp/provider.tf
  infra/gcp/shared/vpc.tf
  infra/gcp/tests/buckets.tf
  infra/gcp/tests/gke.tf
  prow/jobs/custom/infra.yaml
Labels: lgtm, approved, size/L

#505 use 4 replicas for boskos janitor
  prow/cluster/build/boskos-janitor.yaml
Labels: lgtm, size/S, approved

#507 Prow build tests for Backstage stuff
  prow/jobs/generated/knative-extensions/backstage-plugins-main.gen.yaml
  prow/jobs_config/knative-extensions/backstage-plugins.yaml
Labels: lgtm, size/M, approved
