Repository knative/infra, pull requests merged in 2024-01, with the labels that each got.

#295 Add blank config for knative-extensions/backstage-plugins
  prow/jobs/generated/knative-extensions/backstage-plugins-main.gen.yaml
  prow/jobs_config/knative-extensions/backstage-plugins.yaml
Labels: lgtm, size/S, approved

#303 Skip bumping EKB images
  prow/autobump-config/knative-prow-tests.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.10.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.12.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-release-1.10.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-release-1.11.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-release-1.12.yaml
Labels: lgtm, approved, size/L

#306 Add release config for backstage-plugins
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/jobs/generated/knative-extensions/backstage-plugins-main.gen.yaml
  prow/jobs_config/knative-extensions/backstage-plugins.yaml
Labels: lgtm, approved, size/L

#309 Generate Prow image autobump excluded file prefixes
  hack/generate-configs.sh
  hack/verify-codegen.sh
  prow/autobump-config/knative-prow-tests.yaml
  tools/configgen/main.go
  tools/configgen/pkg/autobump.go
Labels: lgtm, approved, size/L

#311 allow knative-admin gh group to rerun jobs
  prow/config.yaml
Labels: lgtm, approved, size/XS

#312 Rollback to jdk20 for EKB
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.10.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.10.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.11.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.12.yaml
Labels: lgtm, approved, size/L

#315 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#319 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#322 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#337 [s390x] add s390x specific prow job config for release-1.13
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.13.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.13.gen.yaml
  prow/jobs/generated/knative/client-release-1.13.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.13.gen.yaml
  prow/jobs/generated/knative/operator-release-1.13.gen.yaml
  prow/jobs/generated/knative/serving-release-1.13.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.13.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-release-1.13.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.13.yaml
  prow/jobs_config/knative/client-release-1.13.yaml
  prow/jobs_config/knative/eventing-release-1.13.yaml
  prow/jobs_config/knative/operator-release-1.13.yaml
  prow/jobs_config/knative/serving-release-1.13.yaml
Labels: lgtm, size/XL, approved

#338 Modify the cronjob timings and add ppc64le specific prow job config for release-1.13
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.13.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.11.gen.yaml
  prow/jobs/generated/knative/client-release-1.12.gen.yaml
  prow/jobs/generated/knative/client-release-1.13.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.12.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.13.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.11.gen.yaml
  prow/jobs/generated/knative/operator-release-1.12.gen.yaml
  prow/jobs/generated/knative/operator-release-1.13.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.11.gen.yaml
  prow/jobs/generated/knative/serving-release-1.12.gen.yaml
  prow/jobs/generated/knative/serving-release-1.13.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.11.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.12.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.13.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.11.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.12.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.13.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event.yaml
  prow/jobs_config/knative/client-release-1.11.yaml
  prow/jobs_config/knative/client-release-1.12.yaml
  prow/jobs_config/knative/client-release-1.13.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing-release-1.11.yaml
  prow/jobs_config/knative/eventing-release-1.12.yaml
  prow/jobs_config/knative/eventing-release-1.13.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/operator-release-1.11.yaml
  prow/jobs_config/knative/operator-release-1.12.yaml
  prow/jobs_config/knative/operator-release-1.13.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving-release-1.11.yaml
  prow/jobs_config/knative/serving-release-1.12.yaml
  prow/jobs_config/knative/serving-release-1.13.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/XL, needs-ok-to-test, approved
