Repository knative/infra, pull requests merged in 2024-02, with the labels that each got.

#341 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#345 Remove eventing-kafka continuous job
  prow/jobs/generated/knative-extensions/eventing-kafka-main.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka.yaml
Labels: lgtm, approved, size/L

#349 drop archived repos
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/autobump-config/knative-prow-tests.yaml
  prow/config.yaml
  prow/jobs/generated/knative-extensions/async-component-main.gen.yaml
  prow/jobs/generated/knative-extensions/scaling-group-main.gen.yaml
  prow/jobs_config/knative-extensions/async-component.yaml
  prow/jobs_config/knative-extensions/scaling-group.yaml
Labels: lgtm, size/XL, approved

#350 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#351 [s390x]: Moving to secure KO_DOCKRE_REPO for s390x arch
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-release-1.13.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.11.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.13.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.11.gen.yaml
  prow/jobs/generated/knative/client-release-1.12.gen.yaml
  prow/jobs/generated/knative/client-release-1.13.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.11.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.12.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.13.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.11.gen.yaml
  prow/jobs/generated/knative/operator-release-1.12.gen.yaml
  prow/jobs/generated/knative/operator-release-1.13.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.11.gen.yaml
  prow/jobs/generated/knative/serving-release-1.12.gen.yaml
  prow/jobs/generated/knative/serving-release-1.13.gen.yaml
  prow/jobs_config/.base.yaml
Labels: lgtm, size/M, approved

#353 bump toolbox to latest commit
  images/prow-tests/Dockerfile
Labels: lgtm, approved, size/XS

#356 drop s390x/ppc CI jobs from main branches
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/XXL, approved

#359 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#361 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#360 Revert "drop s390x/ppc CI jobs from main branches"
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/XXL, approved

#364 Cron job timings & registry name modified for ppc64le jobs
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.13.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.12.gen.yaml
  prow/jobs/generated/knative/client-release-1.13.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.12.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.13.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.12.gen.yaml
  prow/jobs/generated/knative/operator-release-1.13.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.12.gen.yaml
  prow/jobs/generated/knative/serving-release-1.13.gen.yaml
  prow/jobs_config/.base.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.12.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.13.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.12.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.13.yaml
  prow/jobs_config/knative/client-release-1.12.yaml
  prow/jobs_config/knative/client-release-1.13.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing-release-1.12.yaml
  prow/jobs_config/knative/eventing-release-1.13.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/operator-release-1.12.yaml
  prow/jobs_config/knative/operator-release-1.13.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving-release-1.12.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, needs-ok-to-test, approved, size/L

#365 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#366 chore: bump kubectl version in prow-test image
  images/prow-tests/Dockerfile
Labels: lgtm, approved, size/XS

#368 bump go version
  images/prow-tests/Dockerfile
Labels: lgtm, size/S, approved

#371 Cron job timings and registry name modified for ppc64le
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.13.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.12.gen.yaml
  prow/jobs/generated/knative/client-release-1.13.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.12.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.13.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.12.gen.yaml
  prow/jobs/generated/knative/operator-release-1.13.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.12.gen.yaml
  prow/jobs/generated/knative/serving-release-1.13.gen.yaml
  prow/jobs_config/.base.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.12.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker-release-1.13.yaml
  prow/jobs_config/knative-extensions/eventing-kafka-broker.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.12.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event-release-1.13.yaml
  prow/jobs_config/knative-extensions/kn-plugin-event.yaml
  prow/jobs_config/knative/client-release-1.12.yaml
  prow/jobs_config/knative/client-release-1.13.yaml
  prow/jobs_config/knative/client.yaml
  prow/jobs_config/knative/eventing-release-1.12.yaml
  prow/jobs_config/knative/eventing-release-1.13.yaml
  prow/jobs_config/knative/eventing.yaml
  prow/jobs_config/knative/operator-release-1.12.yaml
  prow/jobs_config/knative/operator-release-1.13.yaml
  prow/jobs_config/knative/operator.yaml
  prow/jobs_config/knative/serving-release-1.12.yaml
  prow/jobs_config/knative/serving-release-1.13.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, needs-ok-to-test, approved, size/L

#373 docker_config env variable added for ppc64le jobs
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-main.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/eventing-kafka-broker-release-1.13.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-main.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.12.gen.yaml
  prow/jobs/generated/knative-extensions/kn-plugin-event-release-1.13.gen.yaml
  prow/jobs/generated/knative/client-main.gen.yaml
  prow/jobs/generated/knative/client-release-1.12.gen.yaml
  prow/jobs/generated/knative/client-release-1.13.gen.yaml
  prow/jobs/generated/knative/eventing-main.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.12.gen.yaml
  prow/jobs/generated/knative/eventing-release-1.13.gen.yaml
  prow/jobs/generated/knative/operator-main.gen.yaml
  prow/jobs/generated/knative/operator-release-1.12.gen.yaml
  prow/jobs/generated/knative/operator-release-1.13.gen.yaml
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs/generated/knative/serving-release-1.12.gen.yaml
  prow/jobs/generated/knative/serving-release-1.13.gen.yaml
  prow/jobs_config/.base.yaml
Labels: lgtm, ok-to-test, size/M, approved

#369 bump various tools in our CI image
  images/prow-tests/Dockerfile
Labels: lgtm, size/S, approved
