Repository knative/infra, pull requests merged in 2024-04, with the labels that each got.

#392 add periodic prow job for testing serving + contour + gateway-api
  prow/jobs/generated/knative/serving-main.gen.yaml
  prow/jobs_config/knative/serving.yaml
Labels: lgtm, size/M, approved

#397 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#402 Make tests for contour in net-gateway-api mandatory
  prow/jobs/generated/knative-extensions/net-gateway-api-main.gen.yaml
  prow/jobs_config/knative-extensions/net-gateway-api.yaml
Labels: lgtm, approved, size/XS

#403 temporarily bump all releases images to fix cosign issues
  hack/verify-codegen.sh
  prow/autobump-config/knative-prow-tests.yaml
Labels: lgtm, approved, size/L

#407 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#412 Fix consistentimageexceptions
  prow/autobump-config/knative.yaml
Labels: lgtm, size/S, approved

#421 [main] Update community files
  OWNERS_ALIASES
Labels: size/XS, skip-review

#422 Drop CI config for knative-extensions/net-certmanager
  config/prow/k8s-testgrid/k8s-testgrid.yaml
  prow/autobump-config/knative-prow-tests.yaml
  prow/jobs/generated/knative-extensions/net-certmanager-main.gen.yaml
  prow/jobs/generated/knative-extensions/net-certmanager-release-1.13.gen.yaml
  prow/jobs/generated/knative-extensions/net-certmanager-release-1.14.gen.yaml
  prow/jobs_config/knative-extensions/net-certmanager-release-1.13.yaml
  prow/jobs_config/knative-extensions/net-certmanager-release-1.14.yaml
  prow/jobs_config/knative-extensions/net-certmanager.yaml
Labels: lgtm, size/XL, approved
